version: '3'
services:
  mongodb:
    build: mongodb
    container_name: blockr-dev-stack__validator_mongodb
    networks:
      - blockr
        #volumes:
        # - ./mongodb/data_volume:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myUserAdmin
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    ports:
      - 27018:27017

  p2p:
    container_name: blockr-dev-stack_p2p
    build: blockr-p2p
    ports:
      - "8082:8082"
    networks:
      - blockr

  validator_main:
    container_name: blockr-dev-stack_validator_main
    build: blockr-validator
    ports:
      - "8000:8000"
    networks:
      - blockr
    volumes:
      - ./blockr-validator_main/keys:/keys
       #volumes:
       # - ./blockr-validator_main/database_volume:/app/database
    restart: unless-stopped
    environment:
      - IS_BACKUP=false
      - P2P_SERVER_IP=p2p

  validator_backup:
    container_name: blockr-dev-stack_validator_backup
    build: blockr-validator
    ports:
      - "8001:8000"
    depends_on: 
      - "validator_main"
      - "mongodb"
      - "p2p"
    networks:
      - blockr
    volumes:
      - ./blockr-validator_backup/keys:/keys
    restart: unless-stopped
    environment:
      - IS_BACKUP=true
      - P2P_SERVER_IP=p2p
networks:
  blockr:
    driver: bridge

