pipeline {
  agent any
  stages {
    stage('Setup') {
	    steps {
	      nodejs(nodeJSInstallationName: 'NodeJS') { 
	        sh 'npm --prefix ./contract_validator_ts/ install'
		sh 'npm i @types/jest'
	      } 
	    }
	  }
	  
    stage('Test') {
      steps {
	      nodejs(nodeJSInstallationName: 'NodeJS') { 
	        sh 'npm --prefix ./contract_validator_ts/ run test'
	      } 
      }
    }
    stage('SonarQube analysis') {
      environment {
        scannerHome = tool 'SonarQubeScanner'
      }
      steps {
	      nodejs(nodeJSInstallationName: 'NodeJS') {
          withSonarQubeEnv('SonarQube') {
            sh '${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=blockr-smart-contract -Dsonar.sources=./contract_validator_ts/src -Dsonar.javascript.lcov.reportPaths=./contract_validator_ts/coverage/cobertura-coverage.xml'
          }
          timeout(time: 15, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
          }
        }
      }
    }
  }
}
