pipeline {
  agent any
  stages {
    stage('Setup') {
	    steps {
	      nodejs(nodeJSInstallationName: 'NodeJS') { 
	        sh 'npm --prefix ./contract_validator_ts/ install'
	      } 
	    }
	  }
    stage('SonarQube analysis') {
      environment {
        scannerHome = tool 'SonarQubeScanner'
      }
      steps {
	      nodejs(nodeJSInstallationName: 'NodeJS') {
          withSonarQubeEnv('SonarQube') {
            sh '${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=blockr-smart-contract -Dsonar.sources=/contract_validator_ts/src'
          }
          timeout(time: 15, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
          }
        }
      }
    }
  }
}
